Name:           ros-kinetic-dartsim
Version:        6.3.1
Release:        2%{?dist}
Summary:        ROS dartsim package

Group:          Development/Libraries
License:        BSD
URL:            http://dartsim.github.io/
Source0:        %{name}-%{version}.tar.gz

Requires:       assimp
Requires:       boost-devel
Requires:       bullet-devel
Requires:       eigen3-devel
Requires:       fcl-devel
Requires:       flann-devel
Requires:       freeglut-devel
Requires:       libXi-devel
Requires:       libXmu-devel
Requires:       ros-kinetic-catkin
Requires:       tinyxml-devel
Requires:       tinyxml2-devel
Requires:       urdfdom-devel
BuildRequires:  assimp
BuildRequires:  boost-devel
BuildRequires:  bullet-devel
BuildRequires:  cmake
BuildRequires:  eigen3-devel
BuildRequires:  fcl-devel
BuildRequires:  flann-devel
BuildRequires:  freeglut-devel
BuildRequires:  libXi-devel
BuildRequires:  libXmu-devel
BuildRequires:  pkgconfig
BuildRequires:  tinyxml-devel
BuildRequires:  tinyxml2-devel
BuildRequires:  urdfdom-devel

%description
DART (Dynamic Animation and Robotics Toolkit) is a collaborative, cross-
platform, open source library created by the Georgia Tech Graphics Lab and
Humanoid Robotics Lab, with ongoing support by the University of Washington
Personal Robotics Lab and Open Robotics. DART provides data structures and
algorithms for kinematic and dynamic applications in robotics and computer
animation.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Wed Mar 21 2018 Michael X. Grey <grey@openrobotics.org> - 6.3.1-2
- Autogenerated by Bloom

* Wed Mar 14 2018 Michael X. Grey <grey@openrobotics.org> - 6.3.1-1
- Autogenerated by Bloom

* Tue Mar 13 2018 Michael X. Grey <grey@openrobotics.org> - 6.3.1-0
- Autogenerated by Bloom

